.PHONY: clean All

All:
	@echo "----------Building project:[ Practice-Hello - Debug ]----------"
	@"$(MAKE)" -f  "Practice-Hello.mk"
clean:
	@echo "----------Cleaning project:[ Practice-Hello - Debug ]----------"
	@"$(MAKE)" -f  "Practice-Hello.mk" clean
